#!/usr/bin/env bash
#ytdjkrdt hkjld hrkljdr hkmlt
apt-get -y update
apt-get -y install nginx
sed -i 's/^\(listen\s\+\)80/\180/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Create a simple HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html
