#!/usr/bin/env bash
# This script installs nginx on ubuntu server
sudo apt -y update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
